### ISSUE TITLE
Homebrew linux install "switch command not found"

### ISSUE THREAD

**Issue by cdenneen** [danielfoehrKn/kubeswitch#102]
So followed the Homebrew installation instructions but once the following is run from bashrc it doesn't work (or if manually running it):

```
$ switcher init bash
Error: context with name "init" not found
context with name "init" not found

$ bash --version
bash --version
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
```

**Comment by danielfoehrKn** [comment]
Hi, please use the command `switch` which is a sourced shell function.

**Comment by cdenneen** [comment]
Sorry had to downgrade to 0.7.2 since 0.8.x isn’t supported on AL2 (glibc). Downgrading changed the way to source the function.
