### ISSUE TITLE
kubectx-like completion

### ISSUE THREAD

**Issue by cgrs** [danielfoehrKn/kubeswitch#113]
Hi!

Firstly, thank you for creating this tool, I'm loving it so far!

The main nitpick I have about it is that completion is not behaving the same as with kubectx. I was used to auto-complete contexts using just `kubectx` (actually the alias `kctx`), but with kubeswitch I only have autocompletion for commands. Could this be a bug (maybe shell-related since I'm using Fish), or is it the intended behavior?

**Comment by kinoute** [comment]
I have the same question: is it possible to have auto-completions/suggestions for contexts?

**Comment by danielfoehrKn** [comment]
Hi, have you tried `switch set-context <TAB>` ?

**Comment by kinoute** [comment]
@danielfoehrKn Thanks, it works. I made an alias to use it!

**Comment by cgrs** [comment]
Wow, didn't know about it, thanks! Closing this then 😄
