### ISSUE TITLE
Kubeswitch does not switch kubeconfig on selection

### ISSUE THREAD

**Issue by larssb** [danielfoehrKn/kubeswitch#13]
I'm using [kube-ps1](https://github.com/jonmosco/kube-ps1) in order to show what cluster I'm connected to in my PS1 prompt. However, when I use *kubeswitch/switcher* to switch. I get no error. But the PS1 prompt does NOT change as well as a test with `kubectl get nodes` verifies that I still see the nodes from the cluster I'm trying to switch away from.

* I'm on v0.3.0 of `kubeswitch`
* I'm running `kubectx` and `kubens` at the same time. Is that a problem?

Looking forward to hear from you and thank you

**Comment by danielfoehrKn** [comment]
Hi, you need to use the `switch` script that calls the `switcher` binary under the hood. See [this section ](https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/how_it_works.md)how it works in general.

**Comment by larssb** [comment]
😊 yup  that certainly makes it work. Silly me. I thought that I had sourced the switch.sh file. Thank you.
