### ISSUE TITLE
How can I instruct `switch` to output the list of the context without triggering the fuzzy finder feature?

### ISSUE THREAD

**Issue by karatedog** [danielfoehrKn/kubeswitch#142]
I do not want to disable the fuzzy finder feature I just want `switch` to output a single list of all contexts. I have a few scripts that can work on multiple clusters using `parallel` however that needs input parameters and previously I used  `kubectx` plus some grep to generate that input list.
However switch does not recognize if its output is piped into another tool and turns on the search window.
Thanks.

**Comment by danielfoehrKn** [comment]
Hey, have you checked `switch list-contexts`?

**Comment by karatedog** [comment]
I have to retrain my reading skills while looking at `man` manuals. This is exactly what I needed, thanks.

**Comment by karatedog** [comment]
I have to retrain my reading skills while looking at man manuals. This is exactly what I needed, thanks.
