### ISSUE TITLE
`showPrefix: false` doesn't work together with `id:` ?

### ISSUE THREAD

**Issue by rbo** [danielfoehrKn/kubeswitch#20]
Hi,

the following configuration shows the `.kube` prefix but it should not:

```
$ switch version
Switch:
		version     : v0.4.5
		build date  : 2021-05-22
		go version  : go1.15.12
		go compiler : gc
		platform    : linux/amd64
$ cat ~/.kube/switch-config.yaml
kind: SwitchConfig
version: v1alpha1
showPreview: false
kubeconfigStores:
- kind: filesystem
  id: local
  refreshIndexAfter: 3h
  showPrefix: false
  paths:
  - ~/.kube/config
$switch
```
![image](https://user-images.githubusercontent.com/36604/120281891-ced90700-c2b9-11eb-8745-b6ce8437a78e.png)

If I remove the `id: local` it works as expected. 

Cheers
Robert

**Comment by danielfoehrKn** [comment]
thanks for reporting.

Mhm, I cannot reproduce the issue with the described configuration.
But we can leave the issue open in case other users experience the same problem.

**Comment by rbo** [comment]
I cannot reproduce too anymore.... I close the issue, maybe there was any hidden/special character in the config file.
