### ISSUE TITLE
Possibility to set default context for all new terminals

### ISSUE THREAD

**Issue by florianrusch** [danielfoehrKn/kubeswitch#21]
Hi,

I would like to ask if there is any plan to implement a possibility to set a default context for all future terminals.

Maybe something like:
```shell
$ switch --set-default
$ switch some-context --set-default
```

Currently the workaround for me is to type into every new terminal the following:
```shell
$ switch -
```

**Comment by danielfoehrKn** [comment]
Hi, thanks for reaching out.
I think that is a good idea, but I am not sure if kubeswitch itself is the right place for it.
Kubeswitch itself is a bash script + binary, so it is only invoked when actively switching contexts.
It is not involved when just using `kubectl`.

Why don't you source a function in your `.bashrc` or `.zshrc ` that calls` switch <my-context-name> `on startup of the terminal? That should do the trick.
Alternatively, you can of course change the default kubeconfig file in `.kube/config`.

I hope I understood you right :)

**Comment by florianrusch** [comment]
Hello @danielfoehrKn, thank you for your reply. Yes, I think you have broadly understood me correctly. My current workflow is that I usually use several terminals at the same time. In one for example `watch kubectl get pods` is running and in another I am just working in the same k8s context and namespace.

Most of the time I start with only one terminal (e.g. the one that monitors my resources) and then I spawn another one which then does not use the same k8s context, instead it uses the default context. So I have to select the context again and then also hook into the correct namespace, which is pretty annoying overall.

In the meantime after I created the issue I also discovered, that `switch -` on a newly spawned terminal does not connect to the last context which I selected on another terminal which is still open. (Maybe this is just a layer 8 problem 😅) So currently is't also not a possible solution for me to just call `switch -` in my `.bashrc` or `.zshrc`....

**Comment by danielfoehrKn** [comment]
> In the meantime after I created the issue I also discovered, that switch - on a newly spawned terminal does not connect to the last context which I selected on another terminal which is still open. (Maybe this is just a layer 8 problem 😅) So currently is't also not a possible solution for me to just call switch - in my .bashrc or .zshrc.

The new version 0.4.6 has a command `switch .` to go to the last switched-to context. This could be put in your `.bashrc` so that it runs for new split-panes / terminals.

So if you switch to context A first and then split it up, the new terminals should all be in context A.
However, the namespace will not be kept (always the namespace selected in the original kubeconfig).

This is not the 100% solution, but I am not sure if that is even possible because env variables in shell sessions are not shared, so there is no way I think that `switch` could know which kubeconfig the original terminal session used.

**Comment by danielfoehrKn** [comment]
>  So I have to select the context again and then also hook into the correct namespace, which is pretty annoying overall.

Since version `0.6.0`, the history is also namespace-aware. That means you can switch to the same context + namespace with a single command `switch . `

**Comment by florianrusch** [comment]
Will give it a try next week

**Comment by danielfoehrKn** [comment]
I have been using the `switch .` successfully over the last months to go to the last used context + namespace. 
Considering this issue closed as a more customized "default context" can be implemented on top e.g. by a running `switch .` on terminal startup.
