### ISSUE TITLE
Support EKS

### ISSUE THREAD

**Issue by danielfoehrKn** [danielfoehrKn/kubeswitch#23]
Supporting Amazon EKS seems to be possible
- Golang SDK for EKS can be [found here](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/).
- For authentication with the SDK, see [here](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html)

It seems like that each `region` needs to be specified when authenticating or rely on the default credentials at `.aws/credentials` and   `.aws/config`. This makes configuration in `kubeswitch`  slightly more cumbersome than for GKE.

On top of that, EKS does not have a free tier for development :( 
 If someone uses EKS already and wants to see EKS being supported by `kubeswitch`, this is your chance :)

**Comment by Meroje** [comment]
Hi, letting you know I started playing with this and have a somewhat working implementation over here https://github.com/danielfoehrKn/kubeswitch/compare/master...Meroje:feat/eksstore
I think it's ready for a first PR to gather feedback, will open soon-ish.

**Comment by danielfoehrKn** [comment]
> I think it's ready for a first PR to gather feedback (especially regarding GetKubeconfigForPath), will open soon-ish.

Nice! Looking forward.
