### ISSUE TITLE
Switch ns throws error stating kubeconfig file doesn't exist

### ISSUE THREAD

**Issue by KesavanKing** [danielfoehrKn/kubeswitch#31]
I tried this wonderful tool. This has become everyday handy tool to switch between clusters/kubeconfigs.

But switching ns doesn't work properly

```
switch ns
Error: unable to list namespaces. The kubeconfig file "" does not exist
unable to list namespaces. The kubeconfig file "" does not exist%
```

**Comment by conblem** [comment]
Im facing the same issue

**Comment by danielfoehrKn** [comment]
Sorry for the delay. Could you check if the fix included in [this commit](https://github.com/danielfoehrKn/kubeswitch/commit/e71408abb22be13d4d7e5e42e8088f8fa5f65b64) works for you?

You can use the from source installation method described [here](https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md#from-source).
Thanks a lot!

**Comment by KesavanKing** [comment]
Still I get the same issue.

Always it expects  this `/Users/username/.kube/config` to be present. Then it works correctly.

If I delete the `/Users/username/.kube/config` file it get this error

**Comment by danielfoehrKn** [comment]
Assuming no switch-config file.

KUBECONFIG env set to valid kubeconfig + `/Users/username/.kube/config` not present --> `switch ns` works

KUBECONFIG env not set + `/Users/username/.kube/config` not present --> does throw the above error.
 - `switch` throws: `Error: you need to point kubeswitch to a kubeconfig file`
 - `switch ns` throws `Error:  unable to list namespaces.`

Can you check if you have a KUBECONFIG env variable set if the file `/Users/username/.kube/config` is not present?
