### ISSUE TITLE
Error: failed to get namespace of current context: context with name "/Users/userid/.kube/config" not found

### ISSUE THREAD

**Issue by rubber-ant** [danielfoehrKn/kubeswitch#32]
```
echo $SHELL
/bin/zsh

```
```
switcher version
Switch:
		version     : v0.6.0
		build date  : 2021-12-15
		go version  : go1.17.4
		go compiler : gc
		platform    : darwin/amd6

```
```
switch gke_foo-europe-west1
Error: failed to get namespace of current context: context with name "/Users/userid/.kube/config" not found
```
```
grep context -A1 /Users/userid/.kube/config
contexts:
- context:
    cluster: gke_foo-europe-west1
--
```

when I run only `switch`, the context is listed without issue. 

What I'm doing wrong ?

**Comment by danielfoehrKn** [comment]
> What I'm doing wrong ?

Probably nothing as this is possibly a bug. It seems to be related to the recently introduced namespace switching functionality. 
I will get back to it when finding some time (hopefully next week).
Thanks for reporting already. 

Does `switch` and then checking out the context via the fuzzy search work for you?

**Comment by danielfoehrKn** [comment]
Also you could post a sanitized version of this kubeconfig + your switch-config.yaml

**Comment by rubber-ant** [comment]
after the run `switch` the fuzzy search works and I can select the context without issue. 

Not working:  `switch -d <NAME>   
```
switch -d context1
deleted context context1  from /Users/userid/.kube/.switch_tmp/config.4004739986.tmp
```
Works only if I run `switch -d `and then I select the context. 

```
Not working `switch .`
> switch
switched to context "context1".
>k get namespace
NAME              STATUS   AGE
default           Active   760d
> switch
switched to context "context2".
>k get namespace
NAME              STATUS   AGE
default           Active   601d
> switch .
Error: failed to set namespace "default": failed to set namespace "default": context with name "/Users/userid/.kube/config" not found
```

the kubeconfig is quite a default configuration without any directories and for some reason _switch-config.yaml_ is not even present in the `~/.kube/`

```
 ls -al ~/.kube/
total 56
drwxr-xr-x    7 userid  staff    224 21 Feb 14:56 .
drwxr-xr-x+ 100 userid  staff   3200 21 Feb 15:50 ..
-rw-r--r--    1 userid  staff    666 21 Feb 16:06 .switch_history
drwx------   16 userid  staff    512 21 Feb 16:07 .switch_tmp
drwxr-x---    4 userid  staff    128 20 Feb 14:45 cache
-rw-------@   1 userid  staff  24166 21 Feb 14:48 config
drwxr-xr-x    6 userid  staff    192 21 Feb 11:46 switch-state
```

```
ls -al ~/.kube/switch-state/namespace
total 8
drwxr-xr-x  3 userid  staff   96 21 Feb 09:35 .
drwxr-xr-x  6 userid  staff  192 21 Feb 11:46 ..
-rw-r--r--  1 userid  staff   69 21 Feb 09:35 context1

```

```
grep switch ~/.zshrc
source /usr/local/bin/switch.sh
```

**Comment by danielfoehrKn** [comment]
> the kubeconfig is quite a default configuration without any directories and for some reason switch-config.yaml is not even present in the ~/.kube/

ok thanks, just wanted to check if there is any custom config presents.

> Works only if I run switch -d and then I select the context from fuzzy search

That is expected as switch -d only works on the local copy of the kubeconfig file. So in your case , the context is only deleted from the temporary file, not the original kubeconfig.

I ll have a look at that namespace issue, sorry for the inconvenience.

**Comment by danielfoehrKn** [comment]
Sorry for the delay. I think I have found the problem, but it would be nice if you could test it on your system.

This is the [commit](https://github.com/danielfoehrKn/kubeswitch/commit/824d64e9b503a41f5938f4df89de3377f214d36e).
You can use the from source installation method described [here](https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md#from-source).
Thanks a lot!

**Comment by ipclaudio** [comment]
Hi @danielfoehrKn 

thanks for the fix

```
$ switch -v
Switch:
		version     : v0.6.1
		build date  : 2022-03-31
		go version  : go1.17.6
		go compiler : gc
		platform    : darwin/amd64
```

both of these 2 commands are working now!
```
$ switch gke_foo-europe-west1
switched to context "gke_foo-europe-west1".

$ switch -
```

are you going to look into this? 
```
$ switch -d context1
deleted context context1  from /Users/userid/.kube/.switch_tmp/config.4004739986.tmp
```

**Comment by danielfoehrKn** [comment]
> are you going to look into this?

What is the problem here? For the output I can see that the context was removed - mind you, removed from the temporary kubeconfig file. It will not be removed from the original kubeconfig file. 
To remove the context from the original kubeconfig file, you need to do `export KUBECONFIG=./my-original` and then run `switch -d context1`

**Comment by rubber-ant** [comment]
@danielfoehrKn thanks!
