### ISSUE TITLE
Allow passing namespace to `switch ns`

### ISSUE THREAD

**Issue by streetmapp** [danielfoehrKn/kubeswitch#34]
Right now it doesn't seem like you can pass a namespace to using `switch ns`. For example, if I have a namespace `test`, i should be able to use `switch ns test` and I will be switched over to that namespace. Right now, it pops up the search, which isn't bad. But it could be faster in the cases I know the namespace name I want to switch over to.

**Comment by danielfoehrKn** [comment]
Thanks for the suggestion, I can add this feature in the coming weeks an will let you know

**Comment by danielfoehrKn** [comment]
The feature has been added to the [new release 0.7.0](https://github.com/danielfoehrKn/kubeswitch/releases/tag/0.7.0).
Please reopen the issue if you find any problems.
