### ISSUE TITLE
installation.md link not valid

### ISSUE THREAD

**Issue by antigenius0910** [danielfoehrKn/kubeswitch#35]
https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md
![Screen Shot 2022-05-12 at 2 32 36 PM](https://user-images.githubusercontent.com/5915590/168154064-74133597-231b-4ab6-8e73-a6593e6d71a2.png)

https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/docs/command_completion.md <- this link is not public

seems like extra docs directory were there,
correct one --> https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/command_completion.md

**Comment by antigenius0910** [comment]
PR here https://github.com/danielfoehrKn/kubeswitch/pull/36

**Comment by danielfoehrKn** [comment]
Thank you!
