### ISSUE TITLE
support fish shell?

### ISSUE THREAD

**Issue by sandangel** [danielfoehrKn/kubeswitch#42]
Hi, is it possible to also support fish shell?

**Comment by sandangel** [comment]
@danielfoehrKn hi, could you let me know what should be done to add support for fish shell?

**Comment by danielfoehrKn** [comment]
Central to kubeswitch is the `switch.sh` script [here](https://github.com/danielfoehrKn/kubeswitch/blob/master/hack/switch/switch.sh) that calls the `switcher` binary.
The script has a proper bash shebang, so it might just work under fish. 
I think the first step is to try to use kubeswitch using the fish shell and see if something does not work.

**Comment by sandangel** [comment]
I also suspect that it will only set the environment variable for KUBECONFIG file inside the bash shell itself, all shells.
