### ISSUE TITLE
warning when switching contexts

### ISSUE THREAD

**Issue by mmerickel** [danielfoehrKn/kubeswitch#44]
Every time I switch my shell from one context to another I get a warning to remove the tempfile... seems like overkill or something I'd like to opt out of. I thought it was because I have `alias rm='rm -i'` but I removed the alias and it still happens so I guess kubeswitch is implementing that confirmation itself.

```shell
$ switch
switched to context "foo".
$ switch
remove /Users/michael/.kube/.switch_tmp/config.2360448475.tmp? y
switched to context "bar".
```

It's probably also worth pointing out that if I select `n` then it claims it worked anyway - looks like tmp files are just accumulating in `~/.kube/.switch_tmp`.

**Comment by danielfoehrKn** [comment]
> Every time I switch my shell from one context to another I get a warning to remove the tempfile

Yes that should come from your local setup, as I do not see this message. `rm` is called [here](https://github.com/danielfoehrKn/kubeswitch/blob/ca802d80185e66391d2bd38bc32ddae8c5700d90/hack/switch/switch.sh#L583) to remove the previous `tmp` file.

In addition, there is 
- a cleanup handler for `tmp` files [here](https://github.com/danielfoehrKn/kubeswitch/blob/5d495f852069dd2fe9b757c9c93f415b0a4c0b2a/scripts/cleanup_handler_zsh.sh).
- the `switch clean` command

Though I plan to change to using OS-supported tmp files that are automatically cleaned by the OS such as under `/tmp` or `/var/tmp`

**Comment by mmerickel** [comment]
Would you accept changing it to `rm -f` or do I just need to fork the script? Of course I don’t want to drop the `-i` from my shell just because of this use case. 

Could maybe also support some env vars like `KUBESWITCH_RM="rm -f"`.

**Comment by danielfoehrKn** [comment]
> Would you accept changing it to rm -f 

Yes sure.

> Could maybe also support some env vars like KUBESWITCH_RM="rm -f".

Let's keep it simple and just change it to `rm -f` :)

**Comment by danielfoehrKn** [comment]
I made the change in [this commit](https://github.com/danielfoehrKn/kubeswitch/commit/eab18f5000add3c250dec8ea272284b98f88ae82) - will be in the release 0.7.1 that is released today.

**Comment by danielfoehrKn** [comment]
Please reopen if you still got the issue after upgrading.

**Comment by mmerickel** [comment]
Thank you for the fix!
