### ISSUE TITLE
Supports Vault KV v2?

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [danielfoehrKn/kubeswitch#45]
I can't seem to get switcher to work with my KV v2 secret store. Is v2 supported?

```
$ switcher --debug
DEBU[0000] Using kubeconfig path from flag /Users/blah/.kube/config
DEBU[0000] Added store with kind vault and ID vault.default
DEBU[0000] Added store with kind filesystem and ID filesystem.env-and-flag
WARN[0001] Supressed warnings during the search: 1 error occurred:
	* store "vault.default" returned an error during the search: Error making API request.

URL: GET https://vault.blabla.net/v1/platform-kv/data/kubernetes?list=true
Code: 405. Errors:

* 1 error occurred:
	* unsupported operation



Error: abort
abort%
```

**Comment by danielfoehrKn** [comment]
Hi, thank you for reaching out. I think you are right, V2 is currently not supported.
I think the major thing that would need to be done is to 
- increase the vault SDK version that supports v2 and 
- change vault client usage to use v2 similar to [here](https://github.com/hashicorp/vault-examples/blob/main/examples/_quick-start/go/example.go).
  - for all usages in the vault store such as [here](https://github.com/danielfoehrKn/kubeswitch/blob/5ddadeac4b3f0fda5127f5916da13e71527a56ae/pkg/store/kubeconfig_store_vault.go#L133)

Probably makes sense to only support secrets store v2.

**Comment by danielfoehrKn** [comment]
Done with [release 0.8.0](https://github.com/danielfoehrKn/kubeswitch/releases/tag/0.8.0)
