### ISSUE TITLE
Invalid value: "rancher": kind "rancher" of kubeconfig store is unknown

### ISSUE THREAD

**Issue by amnk** [danielfoehrKn/kubeswitch#54]
I have installed `switch` from Homebrew, and when using example Rancher store config I get this error:
```
Error: the switch configuration file contains errors: kubeconfigStores[0].kind: Invalid value: "rancher": kind "rancher" of kubeconfig store is unknown. Valid kinds are map["azure":{} "eks":{} "filesystem":{} "gardener":{} "gke":{} "vault":{}]
```

brew info:
```
❯ brew info switch
Warning: Treating switch as a formula. For the cask, use homebrew/cask/switch
==> danielfoehrkn/switch/switch: stable 0.7.1
The kubectx for operators.
https://github.com/danielfoehrKn/kubeswitch
/opt/homebrew/Cellar/switch/0.7.1 (3 files, 17.7KB) *
  Built from source on 2022-09-20 at 13:17:10
From: https://github.com/danielfoehrkn/homebrew-switch/blob/HEAD/switch.rb
==> Dependencies
Required: danielfoehrkn/switch/switcher ✔
```

**Comment by danielfoehrKn** [comment]
Hi, sorry, I'll make a release today, then it is included. The READ.ME is a ahead of its time

**Comment by amnk** [comment]
@danielfoehrKn thanks a lot!

**Comment by danielfoehrKn** [comment]
Please let me know if it works as expected, as I personally do not have a Rancher installation.

**Comment by amnk** [comment]
@danielfoehrKn it worked in the end, although I am still testing it. The only small bug I found is that your [docs](https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/stores/rancher/rancher.md) mention `rancherAddress`, while code complains about this and [actually needs](https://github.com/danielfoehrKn/kubeswitch/blob/81ec9d3979f33104dc8c1ce24d586f93d01e9c73/types/config.go#L223) `rancherAPIAddress`
