### ISSUE TITLE
Doesn't switch

### ISSUE THREAD

**Issue by andrey-gava** [danielfoehrKn/kubeswitch#58]
I started to test this from one of the first releases but have the same issue each time.
Execute switcher, expect that it had changed the context but it don't.
```
switcher --debug
DEBU[0000] Using kubeconfig path from flag /home/user/.kube/config 
DEBU[0000] Starting search for store: filesystem         store=filesystem
DEBU[0000] GetKubeconfigForPath: /home/user/.kube/config not cached  store=filesystem
DEBU[0002] GetKubeconfigForPath: /home/user/.kube/config found in cache  store=filesystem
/home/user/.kube/.switch_tmp/config.52797184.tmp
```
In this tmp file the current-context key has right value, the one that I selected. 

switch version v0.7.2
bash 5.1.4(1)-release
context source: ~/.kube/config
Debian GNU/Linux 11 (bullseye)

**Comment by danielfoehrKn** [comment]
Hi, you are not supposed to interface with the `switcher` binary, but switch the sourced `switch` function.  Please [see the installation instructions.](https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md#option-2---manual-installation)
