### ISSUE TITLE
Support for MS Windows

### ISSUE THREAD

**Issue by mar1ged** [danielfoehrKn/kubeswitch#64]
Is there a reason why you don't provide the Windows binaries too ?

First I thought there might be some dependency that doesn't exist on Windows. But I was able to build the binary on my own and it seems to work (have to check this more thoroughly).
Or are there some known things that don't work ?

Additional remarks:
- no, Windows isn't my preferred operating system but sometimes you can't choose ;-)
- I assume that kubeswitch can be used without the switch.sh (or an equivalent) at least to a certain degree

**Comment by danielfoehrKn** [comment]
Windows supported landed in version 0.9.0
