### ISSUE TITLE
add uninstall instructions

### ISSUE THREAD

**Issue by amirtal-cp** [danielfoehrKn/kubeswitch#72]
breaks functionality of aws eks update-kubeconfig

please add uninstall instructions.

**Comment by danielfoehrKn** [comment]
Hi, that's unfortunate. However, uninstallation is generally the reverse of the installation process. If you use homebrew for Mac, they have a build-in mechanism for uninstallation. If you installed it manually, then you need to do the reverse. 
Closing this, as the project does not provide a dedicated installer.

**Comment by tomwidmer** [comment]
You can work around the issue by doing `KUBECONFIG= aws eks update-kubeconfig ...` so that the aws command updates your default kubeconfig file, not the temp one.
