### ISSUE TITLE
FR: Support Tanzu mission control

### ISSUE THREAD

**Issue by rhjensen79** [danielfoehrKn/kubeswitch#79]
Tanzu Mission Control (TMC), supports managing and deployment of many different clusters.
Using the Tanzu cli, it's possible to get the kubeconfig from those managed clusters.

So a feature request is to support Tanzu Mission control, the same way as GCP etc. 

This Issue is created as a placeholder, for ref. I will dig into the documentation, and see if i can make it work. 

Ref : https://tanzu.vmware.com/mission-control

**Comment by danielfoehrKn** [comment]
Hi, I have to rely on community contributions as I don't have a Tanzu installation privately or at work. So if someone sees value in supporting Tanzu, feel free to create a PR.

**Comment by rhjensen79** [comment]
Hi. I had a plan to create this, but my work focus changed, so i don't have access to a tmc tenant anymore.

So let's just close this
